In [2]:
from src.read.processing import Processing

data_loader = Processing()
data_loader.read("connect-4")

,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,...,a34,a35,a36,a37,a38,a39,a40,a41,a42,class
0,b,b,b,b,b,b,b,b,b,b,...,b,b,b,b,b,b,b,b,b,win
1,b,b,b,b,b,b,b,b,b,b,...,b,b,b,b,b,b,b,b,b,win
2,b,b,b,b,b,b,o,b,b,b,...,b,b,b,b,b,b,b,b,b,win
3,b,b,b,b,b,b,b,b,b,b,...,b,b,b,b,b,b,b,b,b,win
4,o,b,b,b,b,b,b,b,b,b,...,b,b,b,b,b,b,b,b,b,win
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67552,x,x,b,b,b,b,o,x,o,b,...,b,b,b,o,o,x,b,b,b,loss
67553,x,x,b,b,b,b,o,b,b,b,...,b,b,b,o,x,o,o,x,b,draw
67554,x,x,b,b,b,b,o,o,b,b,...,b,b,b,o,x,x,o,b,b,loss
67555,x,o,b,b,b,b,o,b,b,b,...,b,b,b,o,x,o,x,x,b,draw
67556,x,o,o,o,x,b,o,b,b,b,...,b,b,b,x,b,b,b,b,b,draw

In [3]:
data_loader.df.columns

Index(['a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7', 'a8', 'a9', 'a10', 'a11',
       'a12', 'a13', 'a14', 'a15', 'a16', 'a17', 'a18', 'a19', 'a20', 'a21',
       'a22', 'a23', 'a24', 'a25', 'a26', 'a27', 'a28', 'a29', 'a30', 'a31',
       'a32', 'a33', 'a34', 'a35', 'a36', 'a37', 'a38', 'a39', 'a40', 'a41',
       'a42', 'class'],
      dtype='object')

In [4]:
data_loader.general_preprocessing()
data_loader.df

,class,a1_o,a1_x,a2_o,a2_x,a3_o,a3_x,a4_o,a4_x,a5_o,...,a37_o,a37_x,a38_o,a38_x,a39_o,a39_x,a40_o,a40_x,a41_o,a41_x
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67552,1,0,1,0,1,0,0,0,0,0,...,1,0,1,0,0,1,0,0,0,0
67553,2,0,1,0,1,0,0,0,0,0,...,1,0,0,1,1,0,1,0,0,1
67554,1,0,1,0,1,0,0,0,0,0,...,1,0,0,1,0,1,1,0,0,0
67555,2,0,1,1,0,0,0,0,0,0,...,1,0,0,1,1,0,0,1,0,1
67556,2,0,1,1,0,1,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0

In [5]:
data_loader.df.shape

(48842, 27)